export { createDatabase } from './connection.js';
export {
  createEmptyDatabase,
  dropDatabaseIfExists,
  listDatabasesWithPrefix,
  makeDatabaseReadOnly,
} from './database-administration.js';
export { readConnectionString, replaceDatabaseName, type ServiceDatabaseKind } from './environment.js';
export { migrateToLatest, type DatabaseKind } from './migrate.js';
export type { ApiClientScope, IdentityDatabase, LoginMethod, SessionChannel, UserStatus } from '../identity/schema.js';
export type {
  AcademicTermType,
  AcademicYearDatabaseStatus,
  AcademicYearStatus,
  SystemDatabase,
} from '../system/schema.js';
export type {
  ApprovalThresholdStatus,
  AssignmentRole,
  AssignmentStatus,
  AttendanceSource,
  AttendanceStatus,
  AuditLogsTable,
  CashAccountType,
  CashflowType,
  CatalogStatus,
  ChildGender,
  ChildStatus,
  ClassStatus,
  ContractType,
  DiscountCalculationMethod,
  FeeDocumentStatus,
  FeeType,
  FilePurpose,
  ImportStatus,
  ImportType,
  InvoiceKind,
  InvoiceStatus,
  LateChargeMethod,
  OnlineMatchStatus,
  OrgUnitStatus,
  OrgUnitType,
  PhotoConsent,
  PhotoConsentMethod,
  PickupConfirmationStatus,
  PickupPersonKind,
  PaymentStatus,
  PaymentType,
  PickupType,
  ReceiptMethod,
  ReceiptStatus,
  RegistrationSource,
  RegistrationStatus,
  SchoolDayChangeType,
  DayHalf,
  LeaveRequestStatus,
  TimesheetDayStatus,
  PayCalculationMethod,
  PayItemKind,
  PayrollStatus,
  PayslipSection,
  TaxBracket,
  SettlementLine,
  SchoolYearDatabase,
  ServiceCalculationMethod,
} from '../school-year/schema.js';
export { DEFAULT_TAX_TABLE_ID } from '../school-year/migrations/0022_create_payrolls.js';
export { MEAL_SERVICE_ID } from '../school-year/migrations/0010_create_fee_catalogs.js';
